### ISSUE TITLE
レビュー依頼

### ISSUE THREAD

**Issue by ms51a** [ms51a/portfolio#29]
* 概要
写真投稿掲示板

- [ ] 掲示板投稿機能
- [ ] ユーザー登録機能
- [ ] お気に入り機能
- [ ] コメント機能
- [ ] タグ作成機能
- [ ] いいね機能

**Comment by tmtkzk0823** [comment]
こちら、何も記載されていなかったので一度お返ししますね。
卒業制作：issueベースの開発カリキュラムを再度ご確認いただき、必要事項を記入、ご用意の上、再度レビュー依頼をしてください。
よろしくお願いします。

**Comment by ms51a** [comment]
お忙しいところご確認いただきありがとうございました。
各issueベースの内容追記いたしました。
お手数ですが、再度ご確認いただければ幸いです。
よろしくお願いいたします。

**Comment by tarakish** [comment]
Projectsにアクセスしましたが、カンバン・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認の上、上記が確認できる状態でご提出をお願いいたします。
![スクリーンショット 2024-05-23 21 58 52](https://github.com/ms51a/portfolio/assets/71510236/774bb813-8103-48e0-a00b-92a4004c756e)

**Comment by ms51a** [comment]
ご指摘の意図を理解できておらず、申し訳ございませんでした。
projectsをpublicに変更したのですが、こちらでよろしいでしょうか。
お手数ですが、ご確認いただければ幸いです。
よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
確認できました。
以下コメントになります。

---

ストーリーポイントが5を超えているものが散見されました。おそらく見通しが不透明なものに多めのポイントを付与しているように見受けられました。ストーリーポイント1,2になるくらいまで細かくissue化することで見通しが鮮明な部分、そうでない部分が可視化され且つ進捗を感じながら開発を進めることができます。一度見直しをしてみてください。

また、デプロイはrails new直後に行うようにissueを作成しておきましょう。

**Comment by ms51a** [comment]
お忙しいところご確認いただきありがとうございます。
お手数ですが、ご確認よろしくお願いいたします。
- ストーリーポイントの目安時間の認識が誤っておりました。申し訳ございません。個人開発におけるプロジェクトマネジメントの目安時間に、ストーリーポイント修正いたしました。
- デプロイissue追加いたしました。

**Comment by tarakish** [comment]
確認できました。LGTMです！
MVPリリースに向けて開発頑張ってください。
